/* SPDX-License-Identifier: MIT */

#include <arch/riscv/riscv.h>
#include <kernel/kernel.h>

#define SCAUSE_INSTRUCTION_ADDR_MISALIGN 0
#define SCAUSE_INSTRUCTION_ACCESS_FAULT 1
#define SCAUSE_ILLEGAL_INSTRUCTION 2
#define SCAUSE_BREAKPOINT 3
#define SCAUSE_LOAD_ADDR_MISALIGNED 4
#define SCAUSE_LOAD_ACCESS_FAULT 5
#define SCAUSE_STORE_AMO_ADDR_MISALIGN 6
#define SCAUSE_STORE_AMO_ACCESS_FAULT 7
#define SCAUSE_ECALL_FROM_U_MODE 8
#define SCAUSE_ECALL_FROM_S_MODE 9
#define SCAUSE_INSTRUCTION_PAGE_FAULT 12
#define SCAUSE_LOAD_PAGE_FAULT 13
#define SCAUSE_STORE_AMO_PAGE_FAULT 15
#define SCAUSE_SOFTWARE_CHECK 18
#define SCAUSE_HARDWARE_CHECK 19

#if defined(__ARCH_is_32bit)
#define SCAUSE_INTERRUPT_BIT 0x80000000L
#else
#define SCAUSE_INTERRUPT_BIT 0x8000000000000000L
#endif

#define SCAUSE_USER_SOFTWARE_INTERRUPT (SCAUSE_INTERRUPT_BIT | 0L)
#define SCAUSE_SUPERVISOR_SOFTWARE_INTERRUPT (SCAUSE_INTERRUPT_BIT | 1L)
#define SCAUSE_SUPERVISOR_TIMER_INTERRUPT (SCAUSE_INTERRUPT_BIT | 5L)
#define SCAUSE_SUPERVISOR_EXTERNAL_INTERRUPT (SCAUSE_INTERRUPT_BIT | 9L)
#define SCAUSE_COUNTER_OVERFLOW_INTERRUPT (SCAUSE_INTERRUPT_BIT | 13L)

/// @brief Prints the scause name and other scause specific info
void dump_scause();

/// @brief Returns a string to the scause name
const char *scause_exception_code_to_string(xlen_t scause);
