stages:
  - build
  - usertests

default:
  image: pandora:5050/robert/vimixos/ci-ubuntu5:26.04
  tags: ["docker"]

variables:
  BUILD_PARAMS: '-j $(nproc) EXTERNAL_KERNEL_FLAGS=-D_SHUTDOWN_ON_PANIC'

.with_build_artifacts:
  artifacts:
    paths:
      - build/boot/filesystem.img
      - build/boot/kernel-vimix
      - build/boot/kernel-vimix.img
      - build_host/root/usr/bin/mkfs
      - build_host/root/usr/bin/fsck.vimixfs
    when: always
    expire_in: 1 week

.build_job:
  stage: build
  extends: .with_build_artifacts

.usertest_job:
  stage: usertests
  artifacts:
    paths:
      - build/logs/
    when: always
    expire_in: 1 week

#before_script:
#  - echo starting

# needs clang 20 or newer, so requires Ubuntu 25.04 or newer
clang_format_check:
  allow_failure: true
  stage: build
  script:
    - tools/tests/check_formatting.sh

# Build all targets
# One per arch also runs the GCC analyzer

# RISC V with M-Mode support
build_rv32m_deb:
  extends: .build_job
  script:
    - eval "make TARGET=rv32m $BUILD_PARAMS BUILD_TYPE=debug"

build_rv32m_rel:
  extends: .build_job
  script:
    - eval "make TARGET=rv32m $BUILD_PARAMS BUILD_TYPE=release"

build_rv64m_deb:
  extends: .build_job
  script:
    - eval "make TARGET=rv64m $BUILD_PARAMS BUILD_TYPE=debug"

build_rv64m_rel:
  extends: .build_job
  script:
    - eval "make TARGET=rv64m $BUILD_PARAMS BUILD_TYPE=release"

# RISCV with SBI support
build_rv32_deb:
  extends: .build_job
  script:
    - eval "make TARGET=rv32 $BUILD_PARAMS BUILD_TYPE=debug"

build_rv32_rel:
  extends: .build_job
  script:
    - eval "make TARGET=rv32 $BUILD_PARAMS BUILD_TYPE=release"

build_rv64_deb:
  extends: .build_job
  script:
    - eval "make TARGET=rv64 $BUILD_PARAMS BUILD_TYPE=debug ANALYZE=1"

build_rv64_rel:
  extends: .build_job
  script:
    - eval "make TARGET=rv64 $BUILD_PARAMS BUILD_TYPE=release"

# clang
# RISCV with SBI support
build_rv32_deb_clang:
  extends: .build_job
  script:
    - eval "make COMPILER=clang TARGET=rv32 $BUILD_PARAMS BUILD_TYPE=debug"

build_rv32_rel_clang:
  extends: .build_job
  script:
    - eval "make COMPILER=clang TARGET=rv32 $BUILD_PARAMS BUILD_TYPE=release"

build_rv64_deb_clang:
  extends: .build_job
  script:
    - eval "make COMPILER=clang TARGET=rv64 $BUILD_PARAMS BUILD_TYPE=debug"

build_rv64_rel_clang:
  extends: .build_job
  script:
    - eval "make COMPILER=clang TARGET=rv64 $BUILD_PARAMS BUILD_TYPE=release"

# ARM
build_arm64_deb:
  extends: .build_job
  script:
    - eval "make TARGET=arm64 $BUILD_PARAMS BUILD_TYPE=debug"

build_arm64_rel:
  extends: .build_job
  script:
    - eval "make TARGET=arm64 $BUILD_PARAMS BUILD_TYPE=release"

#build_arm64_raspi4_deb:
#  extends: .build_job
#  script:
#    - eval "make TARGET=raspi4 $BUILD_PARAMS BUILD_TYPE=debug ANALYZE=1"
#
#build_arm64_raspi4_rel:
#  extends: .build_job
#  script:
#    - eval "make TARGET=raspi4 $BUILD_PARAMS BUILD_TYPE=release"

# tests

usertests_release:
  extends: .usertest_job
  needs:
    - job: build_rv64_rel
      artifacts: true
  script:
    - ./tools/tests/run_test.sh usertests.sh sbi64 "ALL TESTS PASSED"

usertests_release_clang:
  extends: .usertest_job
  needs:
    - job: build_rv64_rel_clang
      artifacts: true
  script:
    - ./tools/tests/run_test.sh usertests.sh sbi64 "ALL TESTS PASSED"

usertests_release_32:
  extends: .usertest_job
  needs:
    - job: build_rv32_rel
      artifacts: true
  script:
    - ./tools/tests/run_test.sh usertests.sh sbi32 "ALL TESTS PASSED"

usertests_debug:
  extends: .usertest_job
  needs:
    - job: build_rv64_deb
      artifacts: true
  script:
    - ./tools/tests/run_test.sh usertests.sh sbi64 "ALL TESTS PASSED"

usertests_debug_clang:
  extends: .usertest_job
  needs:
    - job: build_rv64_deb_clang
      artifacts: true
  script:
    - ./tools/tests/run_test.sh usertests.sh sbi64 "ALL TESTS PASSED"

usertests_memory:
  extends: .usertest_job
  needs:
    - job: build_rv64_rel
      artifacts: true
  script:
    - ./tools/tests/run_test.sh usertests_mem.sh sbi64 "ALL TESTS PASSED" 1 8
    - ./tools/tests/run_test.sh usertests_mem.sh sbi64 "ALL TESTS PASSED" 4 8
    - ./tools/tests/run_test.sh usertests_mem.sh sbi64 "ALL TESTS PASSED" 1 128

usertests_concurrent:
  extends: .usertest_job
  needs:
    - job: build_rv64_rel
      artifacts: true
  script:
    - ./tools/tests/run_test.sh usertests_concurrent.sh sbi64 "ALL TESTS PASSED" 1 32
    - ./tools/tests/run_test.sh usertests_concurrent.sh sbi64 "ALL TESTS PASSED" 2 32
    - ./tools/tests/run_test.sh usertests_concurrent.sh sbi64 "ALL TESTS PASSED" 3 32
    - ./tools/tests/run_test.sh usertests_concurrent.sh sbi64 "ALL TESTS PASSED" 8 32

usertests_failing_rel:
  extends: .usertest_job
  needs:
    - job: build_rv64_rel
      artifacts: true
  script:
    - ./tools/tests/run_test.sh usertests_fail.sh sbi64 "ALL TESTS PASSED" 1 64
    - ./tools/tests/run_test.sh usertests_fail.sh sbi64 "ALL TESTS PASSED" 2 64
    - ./tools/tests/run_test.sh usertests_fail.sh sbi64 "ALL TESTS PASSED" 5 64
    - ./tools/tests/run_test.sh usertests_fail.sh sbi64 "ALL TESTS PASSED" 8 64

fork_test:
  extends: .usertest_job
  needs:
    - job: build_rv64_rel
      artifacts: true
  script:
    - ./tools/tests/run_test.sh forktest.sh sbi64 "ALL TESTS PASSED" 1 32
    - ./tools/tests/run_test.sh forktest.sh sbi64 "ALL TESTS PASSED" 2 32
    - ./tools/tests/run_test.sh forktest.sh sbi64 "ALL TESTS PASSED" 4 32
    - ./tools/tests/run_test.sh forktest.sh sbi64 "ALL TESTS PASSED" 8 32

stack_grows_test:
  extends: .usertest_job
  needs:
    - job: build_rv64_rel
      artifacts: true
  script:
    - ./tools/tests/run_test.sh stack.sh sbi64 "Foo of 1180 is 1180"

grind_test_2:
  extends: .usertest_job
  needs:
    - job: build_rv64_rel
      artifacts: true
  script:
    - ./tools/tests/run_test.sh grind_2.sh sbi64 "grind passed" 1 32
    - ./tools/tests/run_test.sh grind_2.sh sbi64 "grind passed" 2 32
    - ./tools/tests/run_test.sh grind_2.sh sbi64 "grind passed" 4 32
    - ./tools/tests/run_test.sh grind_2.sh sbi64 "grind passed" 8 32

grind_test_8_1:
  extends: .usertest_job
  needs:
    - job: build_rv64_rel
      artifacts: true
  script:
    - ./tools/tests/run_test.sh grind_8.sh sbi64 "grind passed" 1 32

grind_test_8_3:
  extends: .usertest_job
  needs:
    - job: build_rv64_rel
      artifacts: true
  script:
    - ./tools/tests/run_test.sh grind_8.sh sbi64 "grind passed" 3 32

grind_test_8_7:
  extends: .usertest_job
  needs:
    - job: build_rv64_rel
      artifacts: true
  script:
    - ./tools/tests/run_test.sh grind_8.sh sbi64 "grind passed" 7 32

# Spike

spike_boot64_rel:
  extends: .usertest_job
  needs:
    - job: build_rv64m_rel
      artifacts: true
  script:
    - ./tools/tests/run_test.sh echo.sh m-rdisk64 "ALL TESTS PASSED" 4 64 spike

spike_boot32_rel:
  extends: .usertest_job
  needs:
    - job: build_rv32m_rel
      artifacts: true
  script:
    - ./tools/tests/run_test.sh echo.sh m-rdisk32 "ALL TESTS PASSED" 4 64 spike

spike_usertests_misc:
  extends: .usertest_job
  needs:
    - job: build_rv64m_rel
      artifacts: true
  script:
    - ./tools/tests/run_test.sh usertests_misc.sh m-rdisk64 "ALL TESTS PASSED" 4 64 spike

spike_usertests_concurrent:
  extends: .usertest_job
  needs:
    - job: build_rv64m_rel
      artifacts: true
  script:
    - ./tools/tests/run_test.sh usertests_concurrent.sh m-rdisk64 "ALL TESTS PASSED" 4 64 spike

spike_usertests_mem:
  extends: .usertest_job
  needs:
    - job: build_rv64m_rel
      artifacts: true
  script:
    - ./tools/tests/run_test.sh usertests_mem.sh m-rdisk64 "ALL TESTS PASSED" 4 64 spike

# ARM64

arm_arm64_boot64_rel:
  extends: .usertest_job
  needs:
    - job: build_arm64_rel
      artifacts: true
  script:
    - ./tools/tests/run_test.sh echo.sh arm64 "ALL TESTS PASSED"

arm_arm64_boot64_deb:
  extends: .usertest_job
  needs:
    - job: build_arm64_deb
      artifacts: true
  script:
    - ./tools/tests/run_test.sh echo.sh arm64 "ALL TESTS PASSED"

arm_raspi4_boot64_rel:
  extends: .usertest_job
  needs:
    - job: build_arm64_rel
      artifacts: true
  script:
    - ./tools/tests/run_test.sh echo.sh raspi4 "ALL TESTS PASSED"

arm_raspi4_boot64_deb:
  extends: .usertest_job
  needs:
    - job: build_arm64_deb
      artifacts: true
  script:
    - ./tools/tests/run_test.sh echo.sh raspi4 "ALL TESTS PASSED"

arm_arm64_memory_rel:
  extends: .usertest_job
  needs:
    - job: build_arm64_rel
      artifacts: true
  script:
    - ./tools/tests/run_test.sh usertests_mem.sh arm64 "ALL TESTS PASSED" 2 64

arm_arm64_misc_rel:
  extends: .usertest_job
  needs:
    - job: build_arm64_rel
      artifacts: true
  script:
    - ./tools/tests/run_test.sh usertests_misc.sh arm64 "ALL TESTS PASSED"

arm_arm64_concurrent_rel:
  extends: .usertest_job
  needs:
    - job: build_arm64_rel
      artifacts: true
  script:
    - ./tools/tests/run_test.sh usertests_concurrent.sh arm64 "ALL TESTS PASSED" 1 64
    - ./tools/tests/run_test.sh usertests_concurrent.sh arm64 "ALL TESTS PASSED" 2 64
    - ./tools/tests/run_test.sh usertests_concurrent.sh arm64 "ALL TESTS PASSED" 5 64
    - ./tools/tests/run_test.sh usertests_concurrent.sh arm64 "ALL TESTS PASSED" 8 64

arm_arm64_failing_rel:
  extends: .usertest_job
  needs:
    - job: build_arm64_rel
      artifacts: true
  script:
    - ./tools/tests/run_test.sh usertests_fail.sh arm64 "ALL TESTS PASSED" 1 64
    - ./tools/tests/run_test.sh usertests_fail.sh arm64 "ALL TESTS PASSED" 2 64
    - ./tools/tests/run_test.sh usertests_fail.sh arm64 "ALL TESTS PASSED" 5 64
    - ./tools/tests/run_test.sh usertests_fail.sh arm64 "ALL TESTS PASSED" 8 64

arm_arm64_usertests_rel:
  extends: .usertest_job
  needs:
    - job: build_arm64_rel
      artifacts: true
  script:
    - ./tools/tests/run_test.sh usertests.sh arm64 "ALL TESTS PASSED"

arm_raspi4_grind_rel:
  extends: .usertest_job
  needs:
    - job: build_arm64_rel
      artifacts: true
  script:
    - ./tools/tests/run_test.sh grind_8.sh raspi4 "grind passed"

# test tools

test_mkfs:
  stage: usertests
  needs:
    - job: build_rv64_rel
      artifacts: true
  script:
    - ./tools/tests/test_mkfs.sh
