stages:
  - initial_checks
  - build
  - usertests

default:
  image: pandora:5050/robert/vimixos/ci-image:24.04
  tags: ["docker"]

variables:
  BUILD_PARAMS: '-j $(nproc) EXTERNAL_KERNEL_FLAGS=-D_SHUTDOWN_ON_PANIC'

#before_script:
#  - echo starting

# needs clang 20 or newer, so requires Ubuntu 25.04 or newer
format:
  image: pandora:5050/robert/vimixos/ci-image:25.04
  allow_failure: true
  stage: initial_checks
  script:
    - tools/tests/check_formatting.sh

# build with GCC analyzer and boot VIMIX on a recent Ubuntu
build_analyze_2504:
  image: pandora:5050/robert/vimixos/ci-image:25.04
  stage: initial_checks
  script:
    - eval "make $BUILD_PARAMS ANALYZE=1"
  artifacts:
    paths:
      - build/filesystem.img
      - build/boot/kernel-vimix
      - build_host/root/usr/bin/mkfs
    when: always
    expire_in: 1 week

# Build all platforms on GCC 13
build_qemu32_deb:
  image: pandora:5050/robert/vimixos/ci-image:24.04
  stage: build
  script:
    - eval "make $BUILD_PARAMS PLATFORM=qemu32 BUILD_TYPE=debug"
  artifacts:
    paths:
      - build/filesystem.img
      - build/boot/kernel-vimix
      - build_host/root/usr/bin/mkfs
    when: always
    expire_in: 1 week

build_qemu32_rel:
  image: pandora:5050/robert/vimixos/ci-image:24.04
  stage: build
  script:
    - eval "make $BUILD_PARAMS PLATFORM=qemu32 BUILD_TYPE=release"
  artifacts:
    paths:
      - build/filesystem.img
      - build/boot/kernel-vimix
      - build_host/root/usr/bin/mkfs
    when: always
    expire_in: 1 week

build_qemu64_deb:
  image: pandora:5050/robert/vimixos/ci-image:24.04
  stage: build
  script:
    - eval "make $BUILD_PARAMS PLATFORM=qemu64 BUILD_TYPE=debug"
  artifacts:
    paths:
      - build/filesystem.img
      - build/boot/kernel-vimix
      - build_host/root/usr/bin/mkfs
    when: always
    expire_in: 1 week

build_qemu64_rel:
  image: pandora:5050/robert/vimixos/ci-image:24.04
  stage: build
  script:
    - eval "make $BUILD_PARAMS PLATFORM=qemu64 BUILD_TYPE=release"
  artifacts:
    paths:
      - build/filesystem.img
      - build/boot/kernel-vimix
      - build_host/root/usr/bin/mkfs
    when: always
    expire_in: 1 week

build_spike32_deb:
  image: pandora:5050/robert/vimixos/ci-image:24.04
  stage: build
  script:
    - eval "make $BUILD_PARAMS PLATFORM=spike32 BUILD_TYPE=debug"
  artifacts:
    paths:
      - build/filesystem.img
      - build/boot/kernel-vimix
      - build_host/root/usr/bin/mkfs
    when: always
    expire_in: 1 week

build_spike32_rel:
  image: pandora:5050/robert/vimixos/ci-image:24.04
  stage: build
  script:
    - eval "make $BUILD_PARAMS PLATFORM=spike32 BUILD_TYPE=release"
  artifacts:
    paths:
      - build/filesystem.img
      - build/boot/kernel-vimix
      - build_host/root/usr/bin/mkfs
    when: always
    expire_in: 1 week

build_spike64_deb:
  image: pandora:5050/robert/vimixos/ci-image:24.04
  stage: build
  script:
    - eval "make $BUILD_PARAMS PLATFORM=spike64 BUILD_TYPE=debug"
  artifacts:
    paths:
      - build/filesystem.img
      - build/boot/kernel-vimix
      - build_host/root/usr/bin/mkfs
    when: always
    expire_in: 1 week

build_spike64_rel:
  image: pandora:5050/robert/vimixos/ci-image:24.04
  stage: build
  script:
    - eval "make $BUILD_PARAMS PLATFORM=spike64 BUILD_TYPE=release"
  artifacts:
    paths:
      - build/filesystem.img
      - build/boot/kernel-vimix
      - build_host/root/usr/bin/mkfs
    when: always
    expire_in: 1 week

build_visionfive2_deb:
  image: pandora:5050/robert/vimixos/ci-image:24.04
  stage: build
  script:
    - eval "make $BUILD_PARAMS PLATFORM=visionfive2 BUILD_TYPE=debug"
  artifacts:
    paths:
      - build/filesystem.img
      - build/boot/kernel-vimix
      - build_host/root/usr/bin/mkfs
    when: always
    expire_in: 1 week

build_visionfive2_rel:
  image: pandora:5050/robert/vimixos/ci-image:24.04
  stage: build
  script:
    - eval "make $BUILD_PARAMS PLATFORM=visionfive2 BUILD_TYPE=release"
  artifacts:
    paths:
      - build/filesystem.img
      - build/boot/kernel-vimix
      - build_host/root/usr/bin/mkfs
    when: always
    expire_in: 1 week

# tests

usertests_release:
  image: pandora:5050/robert/vimixos/ci-image:24.04
  stage: usertests
  needs:
    - job: build_qemu64_rel
      artifacts: true
  script:
    - ./tools/tests/run_test.sh usertests.sh qemu64 "ALL TESTS PASSED"
  artifacts:
    paths:
      - build/logs/
    when: always
    expire_in: 1 week

usertests_release_32:
  image: pandora:5050/robert/vimixos/ci-image:24.04
  stage: usertests
  needs:
    - job: build_qemu32_rel
      artifacts: true
  script:
    - ./tools/tests/run_test.sh usertests.sh qemu32 "ALL TESTS PASSED"
  artifacts:
    paths:
      - build/logs/
    when: always
    expire_in: 1 week

usertests_debug:
  image: pandora:5050/robert/vimixos/ci-image:24.04
  stage: usertests
  needs:
    - job: build_qemu64_deb
      artifacts: true
  script:
    - ./tools/tests/run_test.sh usertests.sh qemu64 "ALL TESTS PASSED"
  artifacts:
    paths:
      - build/logs/
    when: always
    expire_in: 1 week

fork_test:
  image: pandora:5050/robert/vimixos/ci-image:24.04
  stage: usertests
  needs:
    - job: build_qemu64_rel
      artifacts: true
  script:
    - ./tools/tests/run_test.sh forktest.sh qemu64 "ALL TESTS PASSED"
  artifacts:
    paths:
      - build/logs/
    when: always
    expire_in: 1 week

stack_grows_test:
  image: pandora:5050/robert/vimixos/ci-image:24.04
  stage: usertests
  needs:
    - job: build_qemu64_rel
      artifacts: true
  script:
    - ./tools/tests/run_test.sh stack.sh qemu64 "Foo of 1199 is 1199"
  artifacts:
    paths:
      - build/logs/
    when: always
    expire_in: 1 week

grind_test:
  image: pandora:5050/robert/vimixos/ci-image:24.04
  stage: usertests
  needs:
    - job: build_qemu64_rel
      artifacts: true
  script:
    - ./tools/tests/run_test.sh grind_2.sh qemu64 "grind passed"
  artifacts:
    paths:
      - build/logs/
    when: always
    expire_in: 1 week
