#!/usr/bin/perl -w

# SPDX-License-Identifier: MIT
# Generate usys.S, the stubs for syscalls.

print "# generated by usys.pl - do not edit\n";
print "#include <kernel/unistd.h>\n";
print ".extern errno\n";


# Call syscall
# Check if return value is < 0
#   If so, store negated return value in errno
#   Return -1 instead
sub entry_named {
    my $syscall_name = shift;
    my $name = shift;
    if ($ARGV[0] eq "-riscv")
    {
        print ".global $name\n";
        print "${name}:\n";
        print " li a7, SYS_${syscall_name}\n";
        print " ecall\n";
        print " bge a0, zero, 1f\n";
        print " neg a0, a0\n";
        print " sw a0, errno, t0\n";
        print " li a0,-1\n";
        print "1:\n";
        print " ret\n";
    } elsif ($ARGV[0] eq "-arm64")
    {
        print ".global $name\n";
        print "${name}:\n";
        print " mov x8, #SYS_${syscall_name}\n";
        print " svc #0\n";
        print " cmp w0, #0\n";
        print " b.ge 1f\n";
        print " neg w0, w0\n";
        print " adrp x9, errno\n";
        print " add x9, x9, :lo12:errno\n";
        print " str w0, [x9]\n";
        print " mov x0, #-1\n";
        print "1:\n";
        print " ret\n";
    }
}

sub entry {
    my $name = shift;
    entry_named(${name}, ${name});
}

entry("fork");
entry_named("exit", "_sys_exit"); # needs a wrapper
entry("wait");
entry("pipe");
entry("read");
entry("write");
entry("close");
entry("kill");
entry("execv");
entry("open");
entry("mknod");
entry("unlink");
entry("stat");
entry("fstat");
entry("link");
entry("mkdir");
entry("chdir");
entry("dup");
entry("getpid");
entry("sbrk");
entry("ms_sleep");
entry("uptime");
entry("get_dirent");
entry("reboot");
entry("clock_gettime");
entry("lseek");
entry("rmdir");
entry("mount");
entry("umount");
entry("ioctl");
entry("statvfs");
entry("fstatvfs");
entry("truncate");
entry("ftruncate");
entry("getresuid");
entry("getresgid");
entry("setuid");
entry("setgid");
entry("setresuid");
entry("setresgid");
entry("chown");
entry("fchown");
entry("chmod");
entry("fchmod");
entry("setgroups");
entry("getgroups");
entry("umask");
entry("getcwdlen");
